Repository SOPT-all/35-COLLABORATION-iOS-CGV, pull requests merged in 2024-11, with the labels that each got.

#2 [setting] 프로젝트 초기 세팅
  CGV.xcodeproj/project.pbxproj
  CGV.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CGV.xcodeproj/xcuserdata/yeppi.xcuserdatad/xcschemes/xcschememanagement.plist
  CGV/AppDelegate.swift
  CGV/Application/AppDelegate.swift
  CGV/Application/SceneDelegate.swift
  CGV/Base.lproj/Main.storyboard
  CGV/Presentation/Home/HomeViewController.swift
  CGV/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  CGV/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  CGV/Resource/Assets.xcassets/Contents.json
  CGV/Resource/Base.lproj/LaunchScreen.storyboard
  CGV/Resource/Info.plist
  CGV/SceneDelegate.swift
  CGV/ViewController.swift
Labels: 🎂 suyeon, 🧾 setting

#7 [docs] 깃 이그노어 추가
  .gitignore
  CGV.xcodeproj/project.pbxproj
Labels: 🥭 songhee, 📚 docs

#13 [feat] 인원선택 바텀시트 UI 구현
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Seats/SeatsViewController.swift
  CGV/Presentation/Seats/View/GuestCountSheetView.swift
  CGV/Presentation/Seats/View/SeatsView.swift
  CGV/Presentation/Seats/ViewController/GuestCountSheetViewController.swift
  CGV/Presentation/Seats/ViewController/SeatsViewController.swift
  CGV/Resource/Components/GuestCountButton.swift
Labels: 🛠️ feat, 🎂 suyeon

#15 [feat] 인원선택 바텀시트 기능 구현
  CGV/Presentation/Seats/View/GuestCountSheetView.swift
  CGV/Presentation/Seats/ViewController/GuestCountSheetViewController.swift
  CGV/Presentation/Seats/ViewController/SeatsViewController.swift
  CGV/Resource/Components/GuestCountButton.swift
  CGV/Resource/Extensions/UILabel+.swift
Labels: 🛠️ feat, 🎂 suyeon

#20 [feat] 좌석 선택 뷰 UI 구현
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Seats/Model/SeatsTimeModel.swift
  CGV/Presentation/Seats/View/SeatsCollectionViewCell.swift
  CGV/Presentation/Seats/View/SeatsView.swift
  CGV/Presentation/Seats/ViewController/SeatsViewController.swift
  CGV/Resource/Assets.xcassets/img_seats_selected.imageset/Contents.json
  CGV/Resource/Assets.xcassets/img_seats_selected.imageset/img_seats1_selected.png
  CGV/Resource/Assets.xcassets/img_seats_selected.imageset/img_seats1_selected@2x.png
  CGV/Resource/Assets.xcassets/img_seats_selected.imageset/img_seats1_selected@3x.png
  CGV/Resource/Assets.xcassets/img_seats_unselected.imageset/Contents.json
  CGV/Resource/Assets.xcassets/img_seats_unselected.imageset/img_seats1_unselected.png
  CGV/Resource/Assets.xcassets/img_seats_unselected.imageset/img_seats1_unselected@2x.png
  CGV/Resource/Assets.xcassets/img_seats_unselected.imageset/img_seats1_unselected@3x.png
  CGV/Resource/Base/BaseViewController.swift
Labels: 🛠️ feat, 🎂 suyeon

#21 [feat] 홈 중간 PR
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Home/HomeViewController.swift
  CGV/Presentation/Home/Model/HomeItem.swift
  CGV/Presentation/Home/View/BannerImageCell.swift
  CGV/Presentation/Home/View/BigImageCell.swift
  CGV/Presentation/Home/View/HomeView.swift
  CGV/Presentation/Home/View/MidHeaderView.swift
  CGV/Presentation/Home/View/MidTabBarCell.swift
  CGV/Presentation/Home/View/MidTabBarView.swift
  CGV/Presentation/Home/View/MovieChartCell.swift
  CGV/Presentation/Home/View/ReserveRateCell.swift
  CGV/Presentation/Home/View/TopHeaderView.swift
  CGV/Presentation/Home/View/TopHeaderViewCell.swift
  CGV/Presentation/Home/View/TopTabBarCell.swift
  CGV/Presentation/Home/ViewController/HomeViewController.swift
  CGV/Resource/Extensions/UIFont+.swift
Labels: 🛠️ feat, 🥭 songhee

#23 [fix] 폴더링 변경
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Home/View/Cell/BannerImageCell.swift
  CGV/Presentation/Home/View/Cell/BigImageCell.swift
  CGV/Presentation/Home/View/Cell/MidTabBarCell.swift
  CGV/Presentation/Home/View/Cell/MovieChartCell.swift
  CGV/Presentation/Home/View/Cell/ReserveRateCell.swift
  CGV/Presentation/Home/View/Cell/TopHeaderViewCell.swift
  CGV/Presentation/Home/View/Cell/TopTabBarCell.swift
  CGV/Presentation/Time/Model/RegionInfo.swift
  CGV/Presentation/Time/Model/RegionType.swift
  CGV/Presentation/Time/Model/TheaterInfo.swift
  CGV/Presentation/Time/View/TimeBottomSheetView.swift
  CGV/Presentation/Time/ViewController/TimeBottomSheetViewController.swift
  CGV/Presentation/Time/ViewController/TimeViewController.swift
  CGV/Presentation/Time/ViewController/UnderlineSegmentedControl.swift
  CGV/Resource/Components/TheaterButton.swift
  CGV/Resource/Components/TheaterChipButton.swift
Labels: 🎂 suyeon, ✂️ fix

#26 [feat] 홈 화면 예매율, myCGV, 푸터, 페이지네이션
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Home/Model/HomeItem.swift
  CGV/Presentation/Home/View/Cell/BannerImageCell.swift
  CGV/Presentation/Home/View/Cell/BigImageCell.swift
  CGV/Presentation/Home/View/Cell/BottomFooterCell.swift
  CGV/Presentation/Home/View/Cell/MidTabBarCell.swift
  CGV/Presentation/Home/View/Cell/MovieChartCell.swift
  CGV/Presentation/Home/View/Cell/MyCGVCell.swift
  CGV/Presentation/Home/View/Cell/ProgressShareCell.swift
  CGV/Presentation/Home/View/Cell/ReserveRateCell.swift
  CGV/Presentation/Home/View/Cell/TopHeaderViewCell.swift
  CGV/Presentation/Home/View/Cell/TopTabBarCell.swift
  CGV/Presentation/Home/View/HomeView.swift
  CGV/Presentation/Home/View/MidGrayView.swift
  CGV/Presentation/Home/View/MidHeaderView.swift
  CGV/Presentation/Home/View/MidTabBarView.swift
  CGV/Presentation/Home/View/TopHeaderView.swift
  CGV/Presentation/Home/ViewController/HomeViewController.swift
  CGV/Presentation/Home/ViewController/MidTabBarViewController.swift
Labels: 🛠️ feat, 🥭 songhee

#30 [feat] 시간 선택 화면 구현
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Time/Extenstions/Color+.swift
  CGV/Presentation/Time/Extenstions/Font+.swift
  CGV/Presentation/Time/Model/DateInfo.swift
  CGV/Presentation/Time/Model/MoviePoster.swift
  CGV/Presentation/Time/Model/TheaterTimeTable.swift
  CGV/Presentation/Time/Model/TimeSwiftUIViewModel.swift
  CGV/Presentation/Time/View/Component/DateCell.swift
  CGV/Presentation/Time/View/Component/GradientBackgroundView.swift
  CGV/Presentation/Time/View/Component/TimeCellButton.swift
  CGV/Presentation/Time/View/TimeBottomSheetView.swift
  CGV/Presentation/Time/View/TimeSwiftUIView.swift
  CGV/Presentation/Time/ViewController/TimeBottomSheetViewController.swift
  CGV/Presentation/Time/ViewController/TimeViewController.swift
  CGV/Presentation/Time/ViewController/UnderlineSegmentedControl.swift
Labels: 🛠️ feat, 🙇🏻‍♂️ anyong

#33 [feat] 홈화면 기기대응 코드 추가, 레이아웃 수정
  CGV.xcodeproj/project.pbxproj
  CGV/Presentation/Home/View/Cell/BannerImageCell.swift
  CGV/Presentation/Home/View/Cell/BigImageCell.swift
  CGV/Presentation/Home/View/Cell/BottomFooterCell.swift
  CGV/Presentation/Home/View/Cell/MidTabBarCell.swift
  CGV/Presentation/Home/View/Cell/MovieChartCell.swift
  CGV/Presentation/Home/View/Cell/MyCGVCell.swift
  CGV/Presentation/Home/View/Cell/ProgressShareCell.swift
  CGV/Presentation/Home/View/Cell/ReserveRateCell.swift
  CGV/Presentation/Home/View/Cell/TopHeaderViewCell.swift
  CGV/Presentation/Home/View/Cell/TopTabBarCell.swift
  CGV/Presentation/Home/View/HomeView.swift
  CGV/Presentation/Home/View/MidGrayView.swift
  CGV/Presentation/Home/View/MidHeaderView.swift
  CGV/Presentation/Home/View/MidTabBarView.swift
  CGV/Presentation/Home/View/SectionBackgroundView.swift
  CGV/Presentation/Home/View/TopHeaderView.swift
  CGV/Presentation/Home/ViewController/HomeViewController.swift
  CGV/Presentation/Home/ViewController/MidTabBarViewController.swift
Labels: 🛠️ feat, 🥭 songhee

#34 [feat] 기기 대응 코드 추가 및 레이아웃 충돌 수정
  CGV/Presentation/Time/View/Component/DateCell.swift
  CGV/Presentation/Time/View/Component/GradientBackgroundView.swift
  CGV/Presentation/Time/View/Component/TimeCellButton.swift
  CGV/Presentation/Time/View/TimeBottomSheetView.swift
  CGV/Presentation/Time/View/TimeSwiftUIView.swift
  CGV/Presentation/Time/ViewController/TimeViewController.swift
  CGV/Resource/Components/TheaterButton.swift
  CGV/Resource/Components/TheaterChipButton.swift
Labels: 🛠️ feat, 🙇🏻‍♂️ anyong

#35 [setting] 네트워크 세팅
  .gitignore
  CGV.xcodeproj/project.pbxproj
  CGV.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CGV.xcodeproj/xcuserdata/yeppi.xcuserdatad/xcschemes/xcschememanagement.plist
  CGV/Network/DTO/Base/BaseResponseBody.swift
  CGV/Network/DTO/Base/ErrorResponseBody.swift
  CGV/Network/DTO/Empty/EmptyModel.swift
  CGV/Network/DTO/Protocol/ModelType.swift
  CGV/Network/DTO/Seats/MovieBookingRequest.swift
  CGV/Network/DTO/Seats/MovieBookingResponse.swift
  CGV/Network/DTO/Seats/MovieDetailResponse.swift
  CGV/Network/DTO/Time/MovieTheaterResponse.swift
  CGV/Network/DTO/Time/MovieTimeResponse.swift
  CGV/Network/Environment.swift
  CGV/Network/MoyaLoggingPlugin.swift
  CGV/Network/NetworkResult.swift
  CGV/Network/Service/MovieService.swift
  CGV/Network/Service/TheaterService.swift
  CGV/Network/TargetType/MovieTargetType.swift
  CGV/Network/TargetType/TheaterTargetType.swift
  CGV/Resource/Info.plist
Labels: 🎂 suyeon, 🧾 setting

#40 [feat] 영화 세부 정보 API 연결
  CGV.xcodeproj/project.pbxproj
  CGV.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CGV/Presentation/Seats/View/Cell/SeatsCollectionViewCell.swift
  CGV/Presentation/Seats/View/GuestCountSheetView.swift
  CGV/Presentation/Seats/View/SeatsView.swift
  CGV/Presentation/Seats/ViewController/GuestCountSheetViewController.swift
  CGV/Presentation/Seats/ViewController/SeatsViewController.swift
  CGV/Resource/Extensions/UILabel+.swift
Labels: 🛠️ feat, 🎂 suyeon

#42 [feat] 홈 및 극장 선택 뷰 화면 연결
  CGV/Presentation/Home/View/Cell/MovieChartCell.swift
  CGV/Presentation/Home/ViewController/HomeViewController.swift
  CGV/Presentation/Time/ViewController/TimeViewController.swift
Labels: 🛠️ feat, 🎂 suyeon
